name: ci

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master      # sets up the toolchain
        with: { toolchain: stable }
      - uses: Swatinem/rust-cache@v2             # sccache-backed dependency cache
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test --workspace --locked 